name: Client CI

on:
  push:
    branches: [ develop ]
    paths:
      - "client/**"
  pull_request:
    branches: [ develop ]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install dependencies
      run: cd client && npm install
    - name: Run build
      run: cd client && npm run build
