name: Server CI

on:
  push:
    branches: [ develop ]
    paths:
      - "server/**"
  pull_request:
    branches: [ develop ]
    paths:
      - "server/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install dependencies
      run: cd server && npm install
    - name: Run lint
      run: cd server && npm run lint
